/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import Socket.ServerClass;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Luqman
 */
public class ServerGUI extends javax.swing.JFrame {

    private ServerClass server;

    /**
     * Creates new form GUIServer
     */
    public ServerGUI() {
        super("Chat Server");
        server = null;
        initComponents();
        txtChatRoom.setEditable(false);
        txtEventLog.setEditable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        setLocationRelativeTo(null);
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("socket.png"));
        setIconImage(image);
        lstClient.removeAll();
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(null,
                        "Are you sure to close this window?", "Message Box",
                        JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) {
                    if (server != null) {
                        try {
                            server.stop();
                        } catch (Exception eClose) {
                        }
                        server = null;
                    }
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatRoom = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtPortNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEventLog = new javax.swing.JTextArea();
        btnStartStop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnClearChatRoom = new javax.swing.JButton();
        btnClearEventLog = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtListen = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnClientView = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstClient = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Socket Messenger 1.0");

        txtChatRoom.setColumns(20);
        txtChatRoom.setRows(5);
        jScrollPane1.setViewportView(txtChatRoom);

        jLabel1.setText("Port Number : ");

        txtPortNumber.setText("1337");

        jLabel2.setText("Chat Room");

        jLabel3.setText("Event Log");

        txtEventLog.setColumns(20);
        txtEventLog.setRows(5);
        jScrollPane2.setViewportView(txtEventLog);

        btnStartStop.setText("Start");
        btnStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartStopActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Server");

        btnClearChatRoom.setText("Clear Chat Room");
        btnClearChatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearChatRoomActionPerformed(evt);
            }
        });

        btnClearEventLog.setText("Clear Event Log");
        btnClearEventLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearEventLogActionPerformed(evt);
            }
        });

        txtListen.setEditable(false);
        txtListen.setColumns(20);
        txtListen.setRows(5);
        jScrollPane3.setViewportView(txtListen);

        jLabel5.setText("IP Listen :");

        btnClientView.setText("Client View");
        btnClientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientViewActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstClient);

        jLabel6.setText("Clients");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClearChatRoom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStartStop, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)
                            .addComponent(btnClearEventLog))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClientView, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientView)
                    .addComponent(btnStartStop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnClearChatRoom)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnClearEventLog)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartStopActionPerformed
        if (server != null) {
            server.stop();
            txtListen.setText("");
            server = null;
            txtPortNumber.setEditable(true);
            btnStartStop.setText("Start");
            return;
        }
        int port;
        try {
            port = Integer.parseInt(txtPortNumber.getText().trim());
        } catch (Exception er) {
            appendEvent("Invalid port number");
            return;
        }
        server = new ServerClass(port, this);
        new ServerGUI.ServerRunning().start();
        btnStartStop.setText("Stop");
        txtPortNumber.setEditable(false);

        try {
            String hostName = InetAddress.getLocalHost().getHostName();
            //System.out.println("HostName = " + hostName);
            //System.out.println("HostAddressLocal = "
            //      + InetAddress.getLocalHost().getHostAddress());
            InetAddress[] inetAddresses = InetAddress.getAllByName(hostName);

            for (InetAddress inetAddress : inetAddresses) {
                if (!inetAddress.getHostAddress().contains(":")) {

                    txtListen.append(inetAddress.getHostAddress() + ":" + port + "\n");

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnStartStopActionPerformed

    private void btnClearChatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearChatRoomActionPerformed
        // TODO add your handling code here:
        txtChatRoom.setText("");
    }//GEN-LAST:event_btnClearChatRoomActionPerformed

    private void btnClearEventLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearEventLogActionPerformed
        // TODO add your handling code here:
        txtEventLog.setText("");
    }//GEN-LAST:event_btnClearEventLogActionPerformed

    private void btnClientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientViewActionPerformed
        // TODO add your handling code here:
        ClientGUILogin cgl = new ClientGUILogin();
        cgl.setServerStatus(true);
        cgl.setVisible(true);
    }//GEN-LAST:event_btnClientViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGUI().setVisible(true);
            }
        });
    }

    public void appendClient(ArrayList c) {
        lstClient.removeAll();
        DefaultListModel model = new DefaultListModel();

        for (int i = 0; i < c.size(); i++) {

            model.addElement(c.get(i));
        }
        lstClient.setModel(model);
    }

    public void appendRoom(String str) {
        txtChatRoom.append(str);
        txtChatRoom.setCaretPosition(txtChatRoom.getText().length() - 1);
    }

    public void appendEvent(String str) {
        txtEventLog.append(str);
        txtEventLog.setCaretPosition(txtEventLog.getText().length() - 1);
    }

    class ServerRunning extends Thread {

        public void run() {
            server.start();
            btnStartStop.setText("Start");
            txtPortNumber.setEditable(true);
            appendEvent("Server crashed\n");
            server = null;
        }
    }

    public void windowClosing(WindowEvent e) {

    }

    public void windowClosed(WindowEvent e) {
    }

    public void windowOpened(WindowEvent e) {
    }

    public void windowIconified(WindowEvent e) {
    }

    public void windowDeiconified(WindowEvent e) {
    }

    public void windowActivated(WindowEvent e) {
    }

    public void windowDeactivated(WindowEvent e) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearChatRoom;
    private javax.swing.JButton btnClearEventLog;
    private javax.swing.JButton btnClientView;
    private javax.swing.JButton btnStartStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstClient;
    private javax.swing.JTextArea txtChatRoom;
    private javax.swing.JTextArea txtEventLog;
    private javax.swing.JTextArea txtListen;
    private javax.swing.JTextField txtPortNumber;
    // End of variables declaration//GEN-END:variables
}
